### ISSUE TITLE
Is it possible to inject multiple tags into one field of a message

### ISSUE THREAD

**Issue by bbhands** [favadi/protoc-go-inject-tag#10]
Hi, I tried to inject two different tag names into the same field of a protobuf message like this
```
message Product {
    // @inject_tag: form:"type" validate:"min=0,max=3"
    int32 type = 1;
}
```
But it actually injects nothing
So I'm wondering if I'm misunderstanding the usage or not?

Your help would be greatly appreciated.

**Comment by favadi** [comment]
I just test and it works correctly, can you provide code example and/or logs? Notice that you need to run the protoc-go-inject-tag with .pb.go file, not the .proto file.

**Comment by bbhands** [comment]
The tags to be injected in .pb.go that your test generated is missing
```
type Product struct {
	// @inject_tag: form:"type" validate:"min=0,max=3"
	Type int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
}
```

**Comment by favadi** [comment]
> The tags to be injected in .pb.go that your test generated are missing

Not sure what do you mean, I run `protoc-go-inject-tag -input test.pb.go` and it works as expected.

```
 type Product struct {
        // @inject_tag: form:"type" validate:"min=0,max=3"
-       Type int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
+       Type int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty" form:"type" validate:"min=0,max=3"`
 }
```

**Comment by favadi** [comment]
Close as lack of input.
