### ISSUE TITLE
Support Nested Messages

### ISSUE THREAD

**Issue by tab1293** [favadi/protoc-go-inject-tag#11]
Currently with nested protobuf messages, tags are not injected on the top level message attributes. Is this a known issue/do you have any plans on supporting this?

**Comment by favadi** [comment]
I didn't have this use case, but if you can supply an example proto and
what the result you expected after injection, I will take a look this
weekend.

**Comment by favadi** [comment]
There is no example, so I don't think I can work on, closing.
