### ISSUE TITLE
Injecting a tag should overwrite the existing one (i.e. json)

### ISSUE THREAD

**Issue by vaijab** [favadi/protoc-go-inject-tag#12]
Say if I want to inject a json tag `// @inject_tag: json:"timestamp,omitempty,string"`, to specify field type, `protoc-go-inject-tag` will just append to existing tags. Given that protoc for go adds json tags by default, the end result looks like below:

```
Timestamp int64 `json:"timestamp,omitempty" json:"timestamp,omitempty,string"`
```

What I would like to see is:
```
Timestamp int64 `json:"timestamp,omitempty,string"`
```

**Comment by favadi** [comment]
This sounds reasonable, I will implement this.

**Comment by uynap** [comment]
Hi favadi, how's going for this change? You know the proto3. It's really annoying when deal with "int" and "bool" with "omitempty" hard coded by protobuf.

I have to use some hack ways to get around, for example: 
`ls *.pb.go | xargs -n1 -IX bash -c "sed -e '/bool/ s/,omitempty//' X > X.tmp && mv X{.tmp,}"` 

It would be wonderful if your "protoc-go-inject-tag" is able to overwrite the existing tags.

Thank you in advance.

**Comment by favadi** [comment]
I'm closing this issue, feel free to reopen if it doesn't work.
