### ISSUE TITLE
Parse error when tag's value contain space

### ISSUE THREAD

**Issue by shuLhan** [favadi/protoc-go-inject-tag#14]
I just like to share some error and solution, in case someone stumbled upon the same issue as me.

I try to find the tag specification, but can't found either in reflect package [1] nor in Go spec [2]. Seems like the common ways is to use no space on tag value.

Oh, BTW thank you for this project :+1: !

## Reproduction steps

* Assume that struct already tagged in `test.go`, using `protoc-go-inject-tag`
```
type T struct {
	// @inject_tag: valid:"email, required"
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}
```
* Run `protoc-go-inject-tag`,

  $ protoc-go-inject-tag -input=test.go

## Expected output

No error.

## Actual output

NOTE: additional debugging line `newTagItems t:`

```
2018/05/01 12:29:58 parsing file "test.go" for inject tag comments
2018/05/01 12:29:58 parsed file "test.go", number of fields to inject custom tags: 1
2018/05/01 12:29:58 inject custom tag "valid:\"email, required\"" to expression "Email string `protobuf:\"bytes,1,opt,name=email\" json:\"email,omitempty\"`"
newTagItems t: protobuf:"bytes,1,opt,name=email"
newTagItems t: json:"email,omitempty"
newTagItems t: valid:"email,
newTagItems t: required"
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.newTagItems(0xc420012580, 0x17, 0xc42005e300, 0x2, 0x2)
        /home/ms/Workspaces/myabuy/proofn/src/github.com/favadi/protoc-go-inject-tag/parse.go:58 +0x2fb
main.injectTag(0xc4200c2000, 0x92, 0x600, 0x49, 0x90, 0xc420014341, 0x38, 0xc420012580, 0x17, 0xc420012580, ...)
        /home/ms/Workspaces/myabuy/proofn/src/github.com/favadi/protoc-go-inject-tag/parse.go:69 +0x13e
main.writeFile(0x7ffe952d65f8, 0x7, 0xc42007e3c0, 0x1, 0x1, 0x0, 0x0)
        /home/ms/Workspaces/myabuy/proofn/src/github.com/favadi/protoc-go-inject-tag/file.go:103 +0x27c
main.main()
        /home/ms/Workspaces/myabuy/proofn/src/github.com/favadi/protoc-go-inject-tag/main.go:23 +0x14d
```

This was caused by,
https://github.com/favadi/protoc-go-inject-tag/blob/d6f4c0383edd197e2147286ff57459e1a791c6bf/parse.go#L53

## Solution

Remove space on tag value, e.g. from `valid:"a, b"` to `valid:"a,b"`.

[1] https://golang.org/ref/spec#Tag
[2] https://golang.org/pkg/reflect/#StructTag

**Comment by favadi** [comment]
I've pushed https://github.com/favadi/protoc-go-inject-tag/commit/456a7f4bf0c36012ef5847ae4d9ca9dbee31d0f8 to fixed the panic when injecting tag contains space.

@shuLhan can you give it a try?

**Comment by shuLhan** [comment]
@favadi , it's work again. Thank you again.
