### ISSUE TITLE
Remove all spaces in tag value will break some functionality

### ISSUE THREAD

**Issue by bbhands** [favadi/protoc-go-inject-tag#17]
We're using [this](https://godoc.org/gopkg.in/go-playground/validator.v9#hdr-One_Of) to do struct validation, therefore we need to preserve spaces in tag **value**.

As mentioned [here](https://golang.org/pkg/reflect/#StructTag), tag values can be any golang string literal, so may be we don't need to trim spaces unless we have some other concerns.

Thank you for this awesome tool.

**Comment by favadi** [comment]
I think we could remove this line: https://github.com/favadi/protoc-go-inject-tag/blob/283fda03917205ba30ddce9d43d16f533eb11909/parse.go#L56. Could you test by removing it to see if it works as expected?

**Comment by bbhands** [comment]
Yes, after removing that line, everything works as expected 👍
