### ISSUE TITLE
Consider refactoring into protoc-gen-go plugin

### ISSUE THREAD

**Issue by kenkouot** [favadi/protoc-go-inject-tag#2]
The official `protoc-gen-go` generator exposes a plugin interface. If exposed as a plugin, you can then run: `$ protoc --go_out=plugins=grpc+inject_tags:. *.proto`. This feels a bit more natural I think.

Here is an example of a plugin someone else has implemented: https://github.com/micro/protobuf/blob/master/protoc-gen-go/micro/micro.go

**Comment by kenkouot** [comment]
Specifically, here is the plugin interface: https://godoc.org/github.com/golang/protobuf/protoc-gen-go/generator#Plugin

**Comment by favadi** [comment]
@kenkouot it's good idea, I will try when have some time. If you want to create a PR, I will gladly accept it.

**Comment by kenkouot** [comment]
Awesome, thanks for considering it. I'm pretty tight on time right now but if some becomes available, I'll ping.
