### ISSUE TITLE
inputPath, less verbosity

### ISSUE THREAD

**Issue by xackery** [favadi/protoc-go-inject-tag#24]
Just wanted to note I took a few minutes and tossed this around - https://github.com/xackery/protoc-go-inject-tag/commit/ad68412bdb51fedfb72b210be5cb83e18236bce4

Since I changed the paths to xackery I didn't want to PR back, but highlights are..
* --path argument to import an entire path
* removed all logs except for a single log.Fatal() on error

if you want me to change paths and would be interested in a PR let me know, otherwise feel free to close this issue.

**Comment by favadi** [comment]
A PR is always welcome.

**Comment by lrstanley** [comment]
I think this can be closed -- most of the log verbosity was already solved awhile ago in 01d74ab84c9febc52db8c58624e0e2b8a625bca0, and as far as paths go (being able to use an entire path), https://github.com/favadi/protoc-go-inject-tag/pull/43 should cover this.
