### ISSUE TITLE
change comment parsing location?

### ISSUE THREAD

**Issue by xackery** [favadi/protoc-go-inject-tag#25]
unfortunately tools like https://github.com/grpc-ecosystem/grpc-gateway with swagger generation makes things like screenshot happen
<img width="631" alt="screen shot 2018-09-18 at 9 14 10 pm" src="https://user-images.githubusercontent.com/845670/45730654-d3037b80-bb87-11e8-8e42-cd73ffcbd6f0.png">

**Comment by 8arcturus** [comment]
Any solution on this anyone ?

**Comment by lrstanley** [comment]
if merged, https://github.com/favadi/protoc-go-inject-tag/pull/41 should resolve this.
