### ISSUE TITLE
Cannot inject multiple tags in the same protobuf message

### ISSUE THREAD

**Issue by credli** [favadi/protoc-go-inject-tag#3]
Hi,

It looks like proton-go-inject-tag recognizes only the first tag in the message...

message User {
    // @inject_tag: validate:"required"          <--- Recognized
    string id = 1;
    string type = 2;
    // @inject_tag: validate:"email"              <--- Nope
    string email = 3;
    bool activated = 4;
    // @inject_tag: validate:"required"         <--- Nope
    string phone = 5;
}

**Comment by favadi** [comment]
@credli I haven't tried to reproduce it, but can you add a `@inject_tag` comment to second field? I add inject tag to all the fields and it seems to work fine. I will add a test case to reproduce this and fix later.

**Comment by bclermont** [comment]
I have plenty of `message` with a `@inject_tag` for every  attributes and in generated `.go` all expected injected tags are there

**Comment by credli** [comment]
@favadi you're right, things will work just fine when you have tags on *all* fields, however in my case I only wanted custom tags on two fields. I have created a  PR with a test. PTAL

**Comment by favadi** [comment]
I merged #4, this is fixed.
