### ISSUE TITLE
[Enhancement] Add comment to existing .proto files automatically

### ISSUE THREAD

**Issue by manhdaovan** [favadi/protoc-go-inject-tag#31]
## Context
I have a lot of `.proto` files that contain message definitions,
and adding `// @inject_tag: validate:"omitempty"` before each field of message is so costly.

## Desire
This tool provides an option to add `// @inject_tag: validate:"omitempty"` before each field of message. The tag prefix (`validate` for above example) is given by input, and the tag suffix(`"omitempty"` for above example) is generated bases on the name of message field.

Eg:
```
// message.proto
message SomeMessage {
  string id = 1;
  int32  order_number = 2;
}
```

Then after run the command, (`$./protoc-go-inject-tag -add-cmt tada -input=./message.proto` for example) I should get:
```
// message.proto
message SomeMessage {
  // @inject_tag: tada:"id"
  string id = 1;
  // @inject_tag: tada:"order_number"
  int32  order_number = 2;
}
```

**Comment by favadi** [comment]
This tool is for injecting tag to generated .pb.go files, the feature requested above should be better implement in a separated tool.
