### ISSUE TITLE
input=./pkg/protocol/pb/*.pb.go 

### ISSUE THREAD

**Issue by kamly** [favadi/protoc-go-inject-tag#37]
i want to known can i use `*`  match `.pb.go` file ?

eg. `protoc-go-inject-tag -input=./pkg/protocol/pb/*.pb.go`

**Comment by favadi** [comment]
No, but you can do something like `find ./pkg/protocol/pb/ -name '*.pb.go' -exec protoc-go-inject-tag -input={} \;`

**Comment by kamly** [comment]
why not support it ?
