### ISSUE TITLE
New release to get access to the Verbose logging

### ISSUE THREAD

**Issue by torbjornvatn** [favadi/protoc-go-inject-tag#38]
Hi @favadi. 
Could you make release that contains the Verbose logging and the updated proto deps please.

That would be much appreciated 🙂

**Comment by favadi** [comment]
The latest release [v1.1.0](https://github.com/favadi/protoc-go-inject-tag/releases/tag/v1.1.0) should contain those improvements already.

**Comment by torbjornvatn** [comment]
Ah, ok thanks.
