### ISSUE TITLE
go get github.com/favadi/protoc-go-inject-tag: mkdir C:\Go\bin;E:: The filename,  directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by flanchegong** [favadi/protoc-go-inject-tag#39]
go get -u github.com/favadi/protoc-go-inject-tag                               go get github.com/favadi/protoc-go-inject-tag: mkdir C:\Go\bin;E:: The filename,  directory name, or volume label syntax is incorrect.
--

**Comment by favadi** [comment]
That looks like something with your Go installation. Not sure what I can do here. Feel free to reopen if you can come up with a reproducible report.
