### ISSUE TITLE
feature: more language-specific comment key

### ISSUE THREAD

**Issue by lrstanley** [favadi/protoc-go-inject-tag#45]
Looking over some of the proto files I've written, and the comments/fields aren't very obvious what their purpose is -- primarily around what language they help annotate. I'm thinking we add support for (and recommend it as the default), for `@gotags: ` or similar, since these entries should really only ever be specific to Go. This should help those who use the proto files in other languages.

This is also very easy to make backwards compatible, so shouldn't cause any issues (e.g. `(inject_tags?|gotags?)`.

Thoughts?

**Comment by favadi** [comment]
> I'm thinking we add support for (and recommend it as the default), for @gotags: or similar, since these entries should really only ever be specific to Go.

That sounds like a very good idea to me, feel free to have it implemented.
