### ISSUE TITLE
Project is not working

### ISSUE THREAD

**Issue by Sef1995** [favadi/protoc-go-inject-tag#5]
Hi,

I tried using your project but it's not working. I even tried it with your own pb folder but it does not inject the tag valid:"ip"...

also the unit tests seem to fail? I'm on go version go1.7.4 darwin/amd64

it gives off an error:
 ./example.proto:1:1: expected 'package', found 'IDENT' syntax

How to fix it?

**Comment by favadi** [comment]
What's the problem and how you solve it? :)

**Comment by Sef1995** [comment]
@favadi I was trying to parse the tags in the .proto files while I had to parse the .pb.go files that protoc generates.
