### ISSUE TITLE
does input support find command

### ISSUE THREAD

**Issue by hackneal** [favadi/protoc-go-inject-tag#53]
As I want to inject for multi pb.go files in different director. The directory may be like:

```
golang=>app=>test=>test.pb.go
golang=>sec=>sec.pb.go
```

protoc-go-inject-tag -input=$(find . -name "*.pb.go")

But it seems does not work

**Comment by favadi** [comment]
Some thing like `find . -name '*.pb.go' -exec protoc-go-inject-tag -input={} \;` should work. `protoc-go-inject-tag ` is not yet supported multiple input files. I'll be happy to merge a PR for that feature.

**Comment by hackneal** [comment]
@favadi  you got me. Thanks a lot.
